### ISSUE TITLE
vecmath project doesn't show up in VS2019 solution explorer

### ISSUE THREAD

**Issue by ericwa** [TrenchBroom/vecmath#12]
It's difficult to actually browse the vecmath code in VS, the headers only show up as "External Dependencies" of vecmath-test.

I think we just need to list all the .h files as source files of the vecmath target

**Comment by ericwa** [comment]
Apparently it's actually not implemented yet? That's annoying.
https://developercommunity.visualstudio.com/content/problem/232936/cmake-interface-library-project-shows-nothing-in-c.html

**Comment by ericwa** [comment]
Closing since it seems like there's nothing we can do, as long as it's header-only

**Comment by kduske** [comment]
ugh, that is very annoying
