### ISSUE TITLE
use LU decomposition for invert()

### ISSUE THREAD

**Issue by ericwa** [TrenchBroom/vecmath#13]
I implemented it and it's ~2x faster (Release builds, vs2019) to ~3x faster (Debug build) than the existing one for 4x4 matrices.

Benchmarked the following way (I put it in TB, it's tricky to benchmark in the test suite without having your code executed at compile time): (renamed the old `invert()` implementation to `invert_cramer()`)
```
        vm::mat4x4 TexCoordSystem::fromMatrix(const vm::vec2f& offset, const vm::vec2f& scale) const {
            vm::mat4x4 r;

            const int runs = 100'000;
            {
                QElapsedTimer timer;
                timer.start();  
                    
                for (int i=0; i<runs; i++) {
                    const auto [invertible, result] = invert_cramer(toMatrix(offset, scale));
                    assert(invertible); unused(invertible);
                    r = result;
                }

                qDebug() << "invert_cramer took" << timer.elapsed() << "milliseconds";
            }

            {
                QElapsedTimer timer;
                timer.start();  
                for (int i=0; i<runs; i++) {
                    const auto [invertible, result] = invert(toMatrix(offset, scale));
                    assert(invertible); unused(invertible);
                    r = result;
                }
                qDebug() << "invert took" << timer.elapsed() << "milliseconds";
            }

            return r;
        }
```

example output from release build:
```
invert_cramer took 51 milliseconds
invert took 28 milliseconds
```

example output from debug build:
```
invert_cramer took 1021 milliseconds
invert took 358 milliseconds
```

**Comment by kduske** [comment]
where the code at :-P

**Comment by ericwa** [comment]
figuring out how to commit it :)

**Comment by kduske** [comment]
I can add you as a committer tomorrow. Otherwise you should be able to make a PR from your fork?

**Comment by kduske** [comment]
> Benchmarked the following way (I put it in TB, it's tricky to benchmark in the test suite without having your code executed at compile time): (renamed the old invert() implementation to invert_cramer())

Why is this problematic? Your implementation is constexpr also, why would my implementation be invoked at all?

**Comment by ericwa** [comment]
I wanted to benchmark the runtime performance of the two implementations, my point was just the benchmark would be meaningless if the inverses were calculated at compile time.

I the PR from my fork btw
